import type { JobAlert } from "@/types"

export const mockJobAlerts: JobAlert[] = [
  {
    id: "alert-1",
    title: "New match on LinkedIn",
    message: "Senior Product Manager at Google — 96% profile match",
    portal: "linkedin",
    timestamp: "10 min ago",
    type: "new_job",
    read: false,
  },
  {
    id: "alert-2",
    title: "Application viewed",
    message: "Microsoft recruiter viewed your Product Manager application",
    portal: "naukri",
    timestamp: "1 hour ago",
    type: "status_update",
    read: false,
  },
  {
    id: "alert-3",
    title: "5 new PM roles on Indeed",
    message: "Product Manager roles in Bangalore matching your profile",
    portal: "indeed",
    timestamp: "2 hours ago",
    type: "new_job",
    read: false,
  },
  {
    id: "alert-4",
    title: "Interview reminder",
    message: "Meesho Senior PM — case study round tomorrow at 2 PM",
    portal: "instahyre",
    timestamp: "3 hours ago",
    type: "deadline",
    read: true,
  },
  {
    id: "alert-5",
    title: "High match on Cutshort",
    message: "Group PM at Razorpay — 94% match, apply before deadline",
    portal: "cutshort",
    timestamp: "5 hours ago",
    type: "match",
    read: true,
  },
  {
    id: "alert-6",
    title: "Glassdoor salary insight",
    message: "Senior PM at Google avg salary: ₹50L (above your target)",
    portal: "glassdoor",
    timestamp: "Yesterday",
    type: "match",
    read: true,
  },
  {
    id: "alert-7",
    title: "Wellfound startup roles",
    message: "5 Series-A startups hiring Product Managers remotely",
    portal: "wellfound",
    timestamp: "Yesterday",
    type: "new_job",
    read: true,
  },
  {
    id: "alert-8",
    title: "Foundit profile boost",
    message: "Your profile appeared in 47 recruiter searches this week",
    portal: "foundit",
    timestamp: "2 days ago",
    type: "status_update",
    read: true,
  },
]
