import { format, subDays } from "date-fns"
import type { Job } from "@/types"

const today = () => format(new Date(), "yyyy-MM-dd")

const baseJobs: Omit<Job, "postedAt" | "isNewToday">[] = [
  {
    id: "job-1",
    title: "Senior Software Engineer",
    company: "Google",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹35L – ₹55L",
    matchScore: 94,
    description: "Build scalable backend systems for Google Cloud products.",
    skills: ["Go", "Kubernetes", "Distributed Systems"],
  },
  {
    id: "job-2",
    title: "Full Stack Developer",
    company: "Microsoft",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹28L – ₹45L",
    matchScore: 91,
    description: "Work on Azure portal features using React and .NET.",
    skills: ["React", "TypeScript", "C#", "Azure"],
  },
  {
    id: "job-3",
    title: "Frontend Engineer",
    company: "Flipkart",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹22L – ₹38L",
    matchScore: 89,
    description: "Craft high-performance e-commerce experiences at scale.",
    skills: ["React", "Next.js", "Performance"],
  },
  {
    id: "job-4",
    title: "Backend Engineer",
    company: "Razorpay",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹25L – ₹42L",
    matchScore: 88,
    description: "Design payment APIs handling millions of transactions daily.",
    skills: ["Node.js", "PostgreSQL", "Redis"],
  },
  {
    id: "job-5",
    title: "DevOps Engineer",
    company: "Zomato",
    location: "Gurgaon, India",
    type: "full_time",
    salary: "₹20L – ₹35L",
    matchScore: 85,
    description: "Manage CI/CD pipelines and cloud infrastructure on AWS.",
    skills: ["AWS", "Docker", "Terraform"],
  },
  {
    id: "job-6",
    title: "AI/ML Engineer",
    company: "OpenAI",
    location: "Remote",
    type: "remote",
    salary: "$180k – $250k",
    matchScore: 92,
    description: "Train and deploy large language models for production.",
    skills: ["Python", "PyTorch", "LLMs"],
  },
  {
    id: "job-7",
    title: "Product Engineer",
    company: "Stripe",
    location: "Remote",
    type: "remote",
    salary: "$160k – $210k",
    matchScore: 90,
    description: "Ship payments features end-to-end across the stack.",
    skills: ["Ruby", "React", "SQL"],
  },
  {
    id: "job-8",
    title: "Mobile Developer",
    company: "Swiggy",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹18L – ₹32L",
    matchScore: 82,
    description: "Build consumer-facing Android and iOS applications.",
    skills: ["React Native", "Kotlin", "Swift"],
  },
  {
    id: "job-9",
    title: "Data Engineer",
    company: "Amazon",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹30L – ₹50L",
    matchScore: 87,
    description: "Build data pipelines for AWS analytics products.",
    skills: ["Spark", "Python", "Airflow"],
  },
  {
    id: "job-10",
    title: "Cloud Architect",
    company: "Infosys",
    location: "Pune, India",
    type: "full_time",
    salary: "₹24L – ₹40L",
    matchScore: 84,
    description: "Lead cloud migration projects for enterprise clients.",
    skills: ["AWS", "Azure", "Architecture"],
  },
  {
    id: "job-11",
    title: "React Developer",
    company: "TCS",
    location: "Chennai, India",
    type: "contract",
    salary: "₹15L – ₹25L",
    matchScore: 86,
    description: "6-month contract building enterprise dashboards.",
    skills: ["React", "Redux", "TypeScript"],
  },
  {
    id: "job-12",
    title: "Node.js Developer",
    company: "Wipro",
    location: "Noida, India",
    type: "full_time",
    salary: "₹14L – ₹22L",
    matchScore: 83,
    description: "Develop microservices for banking clients.",
    skills: ["Node.js", "MongoDB", "Express"],
  },
  {
    id: "job-13",
    title: "SRE Engineer",
    company: "PhonePe",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹26L – ₹44L",
    matchScore: 88,
    description: "Ensure 99.99% uptime for India's largest UPI platform.",
    skills: ["Linux", "Prometheus", "Go"],
  },
  {
    id: "job-14",
    title: "UI Engineer",
    company: "Freshworks",
    location: "Chennai, India",
    type: "full_time",
    salary: "₹16L – ₹28L",
    matchScore: 85,
    description: "Design and implement SaaS product interfaces.",
    skills: ["Vue.js", "CSS", "Design Systems"],
  },
  {
    id: "job-15",
    title: "Platform Engineer",
    company: "Atlassian",
    location: "Remote",
    type: "remote",
    salary: "$140k – $190k",
    matchScore: 91,
    description: "Build developer platform tooling for Jira and Confluence.",
    skills: ["Java", "Kubernetes", "GraphQL"],
  },
  {
    id: "job-16",
    title: "Junior Software Engineer",
    company: "CRED",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹12L – ₹20L",
    matchScore: 80,
    description: "Join a fast-paced fintech team building credit products.",
    skills: ["Java", "Spring Boot", "SQL"],
  },
  {
    id: "job-17",
    title: "Tech Lead",
    company: "Meesho",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹40L – ₹65L",
    matchScore: 93,
    description: "Lead a team of 8 engineers building social commerce features.",
    skills: ["Leadership", "System Design", "Python"],
  },
  {
    id: "job-18",
    title: "QA Automation Engineer",
    company: "Paytm",
    location: "Noida, India",
    type: "full_time",
    salary: "₹10L – ₹18L",
    matchScore: 78,
    description: "Automate testing for payment and wallet products.",
    skills: ["Selenium", "Java", "API Testing"],
  },
  {
    id: "job-19",
    title: "Blockchain Developer",
    company: "Polygon",
    location: "Remote",
    type: "remote",
    salary: "$120k – $180k",
    matchScore: 86,
    description: "Build Layer 2 scaling solutions on Ethereum.",
    skills: ["Solidity", "Rust", "Web3"],
  },
  {
    id: "job-20",
    title: "Security Engineer",
    company: "Ola",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹22L – ₹36L",
    matchScore: 84,
    description: "Protect mobility platform from security threats.",
    skills: ["Penetration Testing", "SIEM", "Python"],
  },
  {
    id: "job-21",
    title: "Golang Developer",
    company: "Uber",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹32L – ₹52L",
    matchScore: 90,
    description: "Build real-time ride matching and pricing systems.",
    skills: ["Go", "Kafka", "Microservices"],
  },
  {
    id: "job-22",
    title: "Angular Developer",
    company: "HCL Tech",
    location: "Noida, India",
    type: "contract",
    salary: "₹12L – ₹20L",
    matchScore: 79,
    description: "12-month contract for healthcare portal development.",
    skills: ["Angular", "TypeScript", "RxJS"],
  },
  {
    id: "job-23",
    title: "Python Developer",
    company: "Dream11",
    location: "Mumbai, India",
    type: "full_time",
    salary: "₹20L – ₹34L",
    matchScore: 87,
    description: "Build fantasy sports algorithms and APIs.",
    skills: ["Python", "Django", "Redis"],
  },
  {
    id: "job-24",
    title: "Staff Engineer",
    company: "Netflix",
    location: "Remote",
    type: "remote",
    salary: "$200k – $350k",
    matchScore: 95,
    description: "Architect streaming infrastructure serving 200M+ users.",
    skills: ["Java", "System Design", "AWS"],
  },
]

/** Jobs with dates rotated daily so listings feel freshly updated. */
export function getPortalJobs(): Job[] {
  const dayIndex = new Date().getDate()

  return baseJobs.map((job, index) => {
    const daysAgo = (index + dayIndex) % 7
    const postedAt =
      daysAgo === 0 ? today() : format(subDays(new Date(), daysAgo), "yyyy-MM-dd")

    return {
      ...job,
      postedAt,
      isNewToday: daysAgo === 0,
    }
  })
}

export function getNewJobsToday(): Job[] {
  return getPortalJobs().filter((job) => job.isNewToday)
}

export function getLastUpdatedLabel(): string {
  return format(new Date(), "MMMM d, yyyy")
}
