import { format, subDays } from "date-fns"
import type { Job } from "@/types"

const today = () => format(new Date(), "yyyy-MM-dd")

const baseJobs: Omit<Job, "postedAt" | "isNewToday">[] = [
  {
    id: "job-1",
    title: "Senior Product Manager",
    company: "Google",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹40L – ₹65L",
    matchScore: 96,
    description: "Own roadmap for Google Workspace features used by 3B+ users. Drive PRD, GTM, and cross-functional delivery.",
    skills: ["Roadmapping", "PRD", "Stakeholder Management", "Data Analysis"],
  },
  {
    id: "job-2",
    title: "Product Manager",
    company: "Microsoft",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹32L – ₹52L",
    matchScore: 93,
    description: "Lead Azure consumer product initiatives from discovery through launch.",
    skills: ["Azure", "B2B SaaS", "User Research", "Agile"],
  },
  {
    id: "job-3",
    title: "Associate Product Manager",
    company: "Flipkart",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹18L – ₹28L",
    matchScore: 90,
    description: "0–2 years PM experience. Support category growth and seller experience products.",
    skills: ["Analytics", "A/B Testing", "SQL", "Wireframing"],
  },
  {
    id: "job-4",
    title: "Group Product Manager",
    company: "Razorpay",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹50L – ₹80L",
    matchScore: 94,
    description: "Lead PM team across payments suite. Define multi-year product strategy.",
    skills: ["Leadership", "Strategy", "Fintech", "OKRs"],
  },
  {
    id: "job-5",
    title: "Product Manager — Growth",
    company: "Zomato",
    location: "Gurgaon, India",
    type: "full_time",
    salary: "₹28L – ₹45L",
    matchScore: 88,
    description: "Own acquisition, activation, and retention loops for consumer app.",
    skills: ["Growth", "Funnels", "Experimentation", "Mixpanel"],
  },
  {
    id: "job-6",
    title: "Technical Product Manager",
    company: "Stripe",
    location: "Remote",
    type: "remote",
    salary: "$160k – $220k",
    matchScore: 91,
    description: "Bridge engineering and product for payments API platform.",
    skills: ["APIs", "Technical Depth", "Developer Experience", "SQL"],
  },
  {
    id: "job-7",
    title: "Product Owner",
    company: "Infosys",
    location: "Pune, India",
    type: "full_time",
    salary: "₹16L – ₹26L",
    matchScore: 85,
    description: "Manage backlog and sprint planning for enterprise banking client.",
    skills: ["Scrum", "Jira", "Backlog Grooming", "UAT"],
  },
  {
    id: "job-8",
    title: "Lead Product Manager",
    company: "Swiggy",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹38L – ₹58L",
    matchScore: 92,
    description: "Lead Instamart product vertical. Define OKRs and mentor 3 PMs.",
    skills: ["E-commerce", "Operations", "P&L", "Leadership"],
  },
  {
    id: "job-9",
    title: "Product Manager — AI/ML",
    company: "Amazon",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹35L – ₹55L",
    matchScore: 89,
    description: "Ship AI-powered shopping and recommendation features at scale.",
    skills: ["ML Products", "Personalization", "LLMs", "Metrics"],
  },
  {
    id: "job-10",
    title: "Principal Product Manager",
    company: "Adobe",
    location: "Noida, India",
    type: "full_time",
    salary: "₹45L – ₹70L",
    matchScore: 93,
    description: "Shape creative cloud product vision for India and APAC markets.",
    skills: ["SaaS", "Enterprise", "Vision", "GTM"],
  },
  {
    id: "job-11",
    title: "Product Manager — B2B",
    company: "Freshworks",
    location: "Chennai, India",
    type: "full_time",
    salary: "₹24L – ₹38L",
    matchScore: 87,
    description: "Own CRM module roadmap for SMB and mid-market customers.",
    skills: ["B2B", "CRM", "Customer Discovery", "Roadmaps"],
  },
  {
    id: "job-12",
    title: "Platform Product Manager",
    company: "Atlassian",
    location: "Remote",
    type: "remote",
    salary: "$140k – $190k",
    matchScore: 90,
    description: "Build platform capabilities for Jira and Confluence ecosystem.",
    skills: ["Platform", "APIs", "Ecosystem", "Developer Tools"],
  },
  {
    id: "job-13",
    title: "Product Manager — Payments",
    company: "PhonePe",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹30L – ₹48L",
    matchScore: 91,
    description: "Define UPI and merchant product experiences for 500M+ users.",
    skills: ["Fintech", "UPI", "Compliance", "Metrics"],
  },
  {
    id: "job-14",
    title: "Senior Product Manager — Marketplace",
    company: "Meesho",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹36L – ₹55L",
    matchScore: 94,
    description: "Drive seller and buyer experience for social commerce marketplace.",
    skills: ["Marketplace", "Two-sided", "Pricing", "Growth"],
  },
  {
    id: "job-15",
    title: "Product Manager — Lending",
    company: "CRED",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹32L – ₹50L",
    matchScore: 88,
    description: "Launch and scale credit products for premium user base.",
    skills: ["Lending", "Risk", "Regulatory", "Fintech"],
  },
  {
    id: "job-16",
    title: "Director of Product",
    company: "Uber",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹55L – ₹90L",
    matchScore: 95,
    description: "Lead product org for rides and mobility in South Asia.",
    skills: ["Strategy", "Org Building", "P&L", "Leadership"],
  },
  {
    id: "job-17",
    title: "Product Manager — SaaS",
    company: "Zoho",
    location: "Chennai, India",
    type: "full_time",
    salary: "₹22L – ₹36L",
    matchScore: 86,
    description: "Own feature roadmap for Zoho CRM integrations and automation.",
    skills: ["SaaS", "Integrations", "Workflow", "B2B"],
  },
  {
    id: "job-18",
    title: "Product Manager — Mobile",
    company: "Dream11",
    location: "Mumbai, India",
    type: "full_time",
    salary: "₹26L – ₹42L",
    matchScore: 87,
    description: "Ship engaging fantasy sports features for 180M+ users.",
    skills: ["Mobile", "Engagement", "Gamification", "Analytics"],
  },
  {
    id: "job-19",
    title: "Product Manager — Enterprise",
    company: "Salesforce",
    location: "Hyderabad, India",
    type: "full_time",
    salary: "₹34L – ₹54L",
    matchScore: 90,
    description: "Build enterprise workflow products for India market.",
    skills: ["Enterprise", "Salesforce", "Workflow", "Security"],
  },
  {
    id: "job-20",
    title: "Program Manager",
    company: "Wipro",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹20L – ₹32L",
    matchScore: 82,
    description: "Coordinate cross-team delivery for digital transformation programs.",
    skills: ["Program Management", "Stakeholders", "Risk", "Agile"],
  },
  {
    id: "job-21",
    title: "Product Manager — Data",
    company: "Razorpay",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹28L – ₹44L",
    matchScore: 89,
    description: "Build analytics and reporting products for merchant dashboard.",
    skills: ["Data Products", "SQL", "Dashboards", "BI"],
  },
  {
    id: "job-22",
    title: "VP Product",
    company: "Ola",
    location: "Bangalore, India",
    type: "full_time",
    salary: "₹70L – ₹1.2Cr",
    matchScore: 92,
    description: "Executive product leadership for mobility and EV verticals.",
    skills: ["Executive", "Strategy", "Mobility", "Scale"],
  },
  {
    id: "job-23",
    title: "Product Manager — Consumer",
    company: "Nykaa",
    location: "Mumbai, India",
    type: "full_time",
    salary: "₹24L – ₹40L",
    matchScore: 88,
    description: "Own discovery and checkout experience for beauty e-commerce.",
    skills: ["E-commerce", "UX", "Conversion", "Catalog"],
  },
  {
    id: "job-24",
    title: "Staff Product Manager",
    company: "Netflix",
    location: "Remote",
    type: "remote",
    salary: "$200k – $320k",
    matchScore: 95,
    description: "Define personalization and content discovery strategy globally.",
    skills: ["Personalization", "ML", "Strategy", "Global"],
  },
]

/** Jobs with dates rotated daily so listings feel freshly updated. */
export function getPortalJobs(): Job[] {
  const dayIndex = new Date().getDate()

  return baseJobs.map((job, index) => {
    const daysAgo = (index + dayIndex) % 7
    const postedAt =
      daysAgo === 0 ? today() : format(subDays(new Date(), daysAgo), "yyyy-MM-dd")

    return {
      ...job,
      postedAt,
      isNewToday: daysAgo === 0,
    }
  })
}

export function getNewJobsToday(): Job[] {
  return getPortalJobs().filter((job) => job.isNewToday)
}

export function getLastUpdatedLabel(): string {
  return format(new Date(), "MMMM d, yyyy")
}
