import type { LearningMaterial } from "@/types"

export const mockLearningMaterials: LearningMaterial[] = [
  {
    id: "lm-1",
    title: "System Design Interview Prep",
    description: "Master scalable architecture patterns for FAANG interviews.",
    category: "Interview Prep",
    duration: "12 hours",
    level: "advanced",
    progress: 65,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-2",
    title: "Data Structures & Algorithms",
    description: "Complete DSA roadmap with 200+ curated problems.",
    category: "Fundamentals",
    duration: "40 hours",
    level: "intermediate",
    progress: 42,
    updatedAt: "2026-06-09",
  },
  {
    id: "lm-3",
    title: "React & Next.js Mastery",
    description: "Build production apps with App Router, SSR, and Server Actions.",
    category: "Frontend",
    duration: "18 hours",
    level: "intermediate",
    progress: 78,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-4",
    title: "Resume & LinkedIn Optimization",
    description: "ATS-friendly resume templates and LinkedIn profile strategies.",
    category: "Career",
    duration: "3 hours",
    level: "beginner",
    progress: 100,
    updatedAt: "2026-06-08",
  },
  {
    id: "lm-5",
    title: "Behavioral Interview Guide",
    description: "STAR method, leadership principles, and salary negotiation.",
    category: "Interview Prep",
    duration: "5 hours",
    level: "beginner",
    progress: 30,
    updatedAt: "2026-06-07",
  },
  {
    id: "lm-6",
    title: "AWS Cloud Practitioner",
    description: "Cloud fundamentals, EC2, S3, Lambda, and deployment patterns.",
    category: "Cloud",
    duration: "15 hours",
    level: "beginner",
    progress: 15,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-7",
    title: "SQL for Data Interviews",
    description: "Window functions, joins, and query optimization exercises.",
    category: "Fundamentals",
    duration: "8 hours",
    level: "intermediate",
    progress: 55,
    updatedAt: "2026-06-06",
  },
  {
    id: "lm-8",
    title: "Open Source Contribution",
    description: "Find projects, write PRs, and build your developer portfolio.",
    category: "Career",
    duration: "6 hours",
    level: "intermediate",
    progress: 0,
    updatedAt: "2026-06-10",
  },
]
