import type { LearningMaterial } from "@/types"

export const mockLearningMaterials: LearningMaterial[] = [
  {
    id: "lm-1",
    title: "Product Management Fundamentals",
    description: "Roadmaps, PRDs, prioritization frameworks (RICE, ICE), and stakeholder management.",
    category: "Interview Prep",
    duration: "12 hours",
    level: "beginner",
    progress: 65,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-2",
    title: "PM Case Study Interview Prep",
    description: "Practice product sense, estimation, and GTM cases for top tech companies.",
    category: "Interview Prep",
    duration: "8 hours",
    level: "advanced",
    progress: 42,
    updatedAt: "2026-06-09",
  },
  {
    id: "lm-3",
    title: "SQL for Product Managers",
    description: "Write queries, build dashboards, and make data-driven product decisions.",
    category: "Fundamentals",
    duration: "10 hours",
    level: "intermediate",
    progress: 78,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-4",
    title: "PM Resume & LinkedIn Optimization",
    description: "ATS-friendly PM resume templates and LinkedIn positioning strategies.",
    category: "Career",
    duration: "3 hours",
    level: "beginner",
    progress: 100,
    updatedAt: "2026-06-08",
  },
  {
    id: "lm-5",
    title: "Behavioral Interview for PMs",
    description: "STAR method, leadership principles, and executive communication.",
    category: "Interview Prep",
    duration: "5 hours",
    level: "intermediate",
    progress: 30,
    updatedAt: "2026-06-07",
  },
  {
    id: "lm-6",
    title: "Product Analytics & Metrics",
    description: "North star metrics, funnel analysis, cohort retention, and A/B testing.",
    category: "Fundamentals",
    duration: "15 hours",
    level: "intermediate",
    progress: 15,
    updatedAt: "2026-06-10",
  },
  {
    id: "lm-7",
    title: "User Research for PMs",
    description: "Interviews, surveys, usability testing, and synthesis techniques.",
    category: "Fundamentals",
    duration: "8 hours",
    level: "beginner",
    progress: 55,
    updatedAt: "2026-06-06",
  },
  {
    id: "lm-8",
    title: "B2B SaaS Product Strategy",
    description: "Enterprise sales cycles, PLG motions, and platform product thinking.",
    category: "Career",
    duration: "6 hours",
    level: "advanced",
    progress: 0,
    updatedAt: "2026-06-10",
  },
]
